name: Front-matter check
on:
  pull_request:
    paths:
      - 'tutorials/**/*.qmd'
      - '_data/topics.yml'
      - 'R/check_frontmatter.R'

jobs:
  frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::yaml

      - name: Validate front-matter
        run: Rscript R/check_frontmatter.R
